language: python
python:
  - "2.7"
install:
  - pip install codecov pytest pytest-cov -r requirements.txt
script:
  - py.test --cov=.
  - coverage run --source . --append ./setup.py build
  - coverage run --source . --append ./setup.py install
after_script:
  - codecov
addons:
  apt:
    packages:
    - libgammu-dev
    - python-wxgtk2.8
    - libbluetooth-dev
