language: python
python:
  - "2.7"
sudo: false
install:
  - pip install codecov pytest pytest-cov -r requirements.txt
script:
  - py.test --cov=.
  - coverage run --source . --append ./setup.py build
  - coverage run --source . --append ./setup.py install
after_script:
  - codecov
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
    - gammu
    packages:
    - libgammu-dev
    - python-wxgtk2.8
    - libbluetooth-dev
